//@version=5
indicator("Mayer Multiple", overlay=true)

mayer_multiple = close / ta.sma(close, 200)

plot_color = (mayer_multiple < 0.55) ? color.new(#1d5e24, 0) :
              (mayer_multiple < 0.70) ? color.new(#49814c, 0) :
              (mayer_multiple < 0.85) ? color.new(#74a576, 0) :
              (mayer_multiple < 1.00) ? color.new(#9fcba2, 0) :
              (mayer_multiple < 1.175) ? color.new(#FFFFFF, 0) :
              (mayer_multiple < 1.35) ? color.new(#eeb9ba, 0) :
              (mayer_multiple < 1.525) ? color.new(#dea3a5, 0) :
              (mayer_multiple < 1.7) ? color.new(#ce8c8f, 0) :
              (mayer_multiple < 1.875) ? color.new(#be7679, 0) :
              (mayer_multiple < 2.05) ? color.new(#ad5f63, 0) :
              (mayer_multiple < 2.225) ? color.new(#9d494d, 0) :
              (mayer_multiple < 2.4) ? color.new(#8d3237, 0) :
              color.new(#7d1c21, 0) 

plot(mayer_multiple, color=plot_color, title="Mayer Multiple", linewidth=1)

breakout_fill_color = mayer_multiple > 2.4 ? color.new(#7d1c21, 66) : mayer_multiple < 0.55 ? color.new(#1d5e24, 66) : mayer_multiple < 0.7 ? color.new(#49814c, 66) : na
bgcolor(breakout_fill_color)
